feat: implement Tile component on @dashboard module
nexxtway/rainbow-modules pull request #106
Opened 2020-09-16 15:58 UTC by yvmunayev

fix: #100 

## Changes proposed in this PR:
- feat: implement Tile component on @dashboard module

2020-09-17 18:14 UTC, TahimiLeonBravo requested changes

2020-09-17 18:14 UTC, TahimiLeonBravo commented on packages/dashboard/src/components/Tile/checkmark.js
> +    const { className, style } = props;
I think we should consider using the ones on icons module

2020-09-17 18:54 UTC, TahimiLeonBravo requested changes

2020-09-17 18:54 UTC, TahimiLeonBravo commented on packages/dashboard/src/components/Tile/index.js
> +            <StyledInput
I think we should not use an input when the component is presentational, it only should be used as an input with `focus` and `selected` styles when it is used inside the `TilePicker` component

2020-09-17 18:54 UTC, TahimiLeonBravo commented on packages/dashboard/src/components/Tile/index.js
> +            <StyledInput
@maxxgreene @LeandroTorresSicilia I think we should discuss that

2020-09-18 15:00 UTC, TahimiLeonBravo requested changes

2020-09-18 15:00 UTC, TahimiLeonBravo commented on packages/dashboard/src/components/Tile/index.js
> +                <StyledLabelInput htmlFor={inputId} style={{ backgroundColor }}>
let's use `StyledLabel` instead `StyledLabelInput`

2020-09-18 15:00 UTC, TahimiLeonBravo commented on packages/dashboard/src/components/Tile/index.js
> +                    <StyledLabel style={labelStyle}>{label}</StyledLabel>
let's use `StyledLabelText` instead `StyledLabel`

2020-09-18 15:53 UTC, TahimiLeonBravo commented
@yvmunayev add documentation for the component

2020-09-19 02:24 UTC, LeandroTorresSicilia commented on packages/dashboard/src/components/Tile/helpers/__test__/isChecked.spec.js
> +        expect(isChecked(true, [0, 1, 2], 1)).toBe(true);
in order to improve readability, we should use only one argument as an object thus we can add names to the parameters like:
```icChecked({
    multiple: true,
    value: [...],
    name: 1,
    ...
})```

2020-09-19 02:25 UTC, LeandroTorresSicilia commented on packages/dashboard/src/components/Tile/helpers/__test__/isChecked.spec.js
> +    it('should return false when is multiple and name is include in value', () => {
not include

2020-09-19 02:28 UTC, LeandroTorresSicilia commented on packages/dashboard/src/components/Tile/index.js
> +    value: PropTypes.number,
the value can be '1k'

2020-09-19 02:34 UTC, LeandroTorresSicilia commented on packages/dashboard/docs/stories/Tile.story.js
> +    `;
you can move this outside

2020-09-19 02:34 UTC, TahimiLeonBravo requested changes

2020-09-19 02:34 UTC, TahimiLeonBravo commented on packages/dashboard/src/components/Tile/index.js
> +    color: '#333333',
it should work with the theme, we should use `getContastText`

2020-09-19 02:34 UTC, TahimiLeonBravo commented on packages/dashboard/src/components/Tile/index.js
> +    backgroundColor: '#ffffff',
it should work with the theme, we should use the `mainBackground`

2020-09-19 02:35 UTC, merged