feat: implement editable on `ColoredStatusColumn` component
nexxtway/rainbow-modules pull request #305
Opened 2021-01-22 03:22 UTC by HellWolf93

fix: #298

2021-01-22 18:20 UTC, LeandroTorresSicilia commented on packages/listview/src/components/ColoredStatusColumn/index.js
> +                        {getOptions()}
let's use this declarative:
```<Options />```
create Options components that make the iteration

2021-01-22 18:28 UTC, LeandroTorresSicilia commented on packages/listview/src/components/ColoredStatusColumn/index.js
> +    const hasPopup = isEditable ? 'listbox' : null;
since this is not a boolean I think we should use other name: ariaHaspopup

2021-01-22 18:29 UTC, LeandroTorresSicilia commented on packages/listview/src/components/ColoredStatusColumn/index.js
> +                    component={ColoredOption}
pass a unique key to the mapping items

2021-01-23 05:44 UTC, TahimiLeonBravo requested changes

2021-01-23 05:44 UTC, TahimiLeonBravo commented on packages/listview/src/components/ColoredStatusColumn/option.js
> +    return <StyledHeader>Change Status</StyledHeader>;
We should add a new prop for the header because it should support internationalization

2021-01-23 05:45 UTC, TahimiLeonBravo commented
@HellWolf93 we should return the focus to the cell when close the dropdown

2021-01-23 05:47 UTC, TahimiLeonBravo commented
@HellWolf93 we should add some styles to the cell selected

2021-01-23 05:49 UTC, TahimiLeonBravo commented
@HellWolf93 we should remove the gray color outside the status option
<img width="341" alt="Screen Shot 2021-01-22 at 11 48 08 PM" src="https://user-images.githubusercontent.com/32083556/105570063-78a4f780-5d0c-11eb-9bf2-f913bbcd5010.png">

2021-01-25 15:18 UTC, LeandroTorresSicilia commented on packages/listview/src/components/ColoredStatusColumn/index.d.ts
> +    dropdownHeader: ReactNode;
this is not required

2021-01-25 15:19 UTC, LeandroTorresSicilia commented on packages/listview/src/components/ColoredStatusColumn/index.js
> +    const header = dropdownHeader || dropdownHeaderLabel;
we need to discuss this prop name and then if we pass this as a prop then we don't need the dropdownHeaderLabel

2021-01-25 15:19 UTC, merged